### ISSUE TITLE
docker-compose.yml: No such file or directory

### ISSUE THREAD

**Issue by Arsaev** [wshihadeh/docker-deployment-action#18]
Hi I have here problem with docker-compose.yml: No such file or directory.

Here is my  workflow code 
```
name: Github to DigitalOcean droplet

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: "registry.digitalocean.com/name"
  IMAGE_NAME: "name"

jobs:
  # tests:
    # in the best case you would want to run some tests here
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest .

      - name: Tag container
        run: docker tag -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry as latest
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest

      - name: Push image to DigitalOcean Container Registry with hash
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
  
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: Deploy to Docker compose
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
          stack_file_name: docker-compose.yml
          keep_files: 5
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: /root/my-deployment
          args: up -d
          docker_prune: 'false'
          pull_images_first: 'true'
```

Error output
```
 Registering SSH keys...
Agent pid 10
Identity added: /github/home/.ssh/id_rsa (***@NAME)
Add known hosts
Execute Over SSH: mkdir -p /***/my-deployment/stacks || true
Warning: Permanently added '***' (ECDSA) to the list of known hosts.
docker-compose.yml: No such file or directory
```
