### ISSUE TITLE
Error when deploying with swarm mode (unknown flag: --log-level)

### ISSUE THREAD

**Issue by parsilver** [wshihadeh/docker-deployment-action#2]
```
      - name: Deploy
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@xxxxxx
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          stack_file_name: stack.yml
          args: --with-registry-auth account
```

and I'm stuck here.
```
Registering SSH keys...
Agent pid 9
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
Add known hosts
Connecting to root@xxxxxx...
unknown flag: --log-level
See 'docker stack deploy --help'.
```

**Comment by wshihadeh** [comment]
can you try again ?

**Comment by parsilver** [comment]
I have a new error. >.<

How can I put args?
I'm sorry again.

```
   - name: Deploy
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@xxxxxx
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          stack_file_name: stack.yml
          args: --with-registry-auth account
```



```
Registering SSH keys...
Agent pid 9
Add known hosts
Connecting to root@xxxxxxx...
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
unknown flag: --with-registry-auth account
See 'docker stack deploy --help'.
```
