### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by 1zilc** [wshihadeh/docker-deployment-action#21]
Hello, thank you very much for creating this action. It is very easy to use. I recently encountered problems when pulling images from a private docker registry with htpasswd authentication and running. I hope to get your help. The docker-compose-action log is as follows

```bash
Registering SSH keys...
Agent pid 11
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
Add known hosts
Connecting to ***... Command: docker-compose  --log-level debug --host ssh://***:22 -f docker-compose.yaml up -d
Using configuration files: ./docker-compose.yaml
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
No config file found
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
No config file found
/usr/lib/python3.8/site-packages/paramiko/client.py:835: UserWarning: Unknown ssh-ed25519 host key for xxx.xxx.xx.xxx: b'a30e3cb6de6c7a8a6cf0fef82cb0b734'
  warnings.warn(
ssh://localhost:None "GET /v1.25/networks/workspace_default HTTP/1.1" 200 1563
ssh://localhost:None "GET /v1.25/info HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/networks/workspace_default HTTP/1.1" 200 1563
ssh://localhost:None "GET /v1.25/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dworkspace%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dworkspace%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/containers/45feef820155bd5f05034fb353e6d49d9c2821e6ddbd4f82ee849c3a164a99eb/json HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/containers/d680e0237481bde07b04a732fa5e9a38227e1a37d4ca4fc4b3d650e642bc0bda/json HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/containers/3f2aee9e458e3a93c36d18d324b6bf165b3880157897b13cbd319a547b095b22/json HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/containers/a9ce67f95fd9cd82ae60ddab3ae9adf00b9a4e7aa2891a594551fcf9a24c5a2a/json HTTP/1.1" 200 None
Found orphan containers (webpack-demo) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
ssh://localhost:None "GET /v1.25/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dworkspace%22%2C+%22com.docker.compose.service%3Dhook-express%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1491
ssh://localhost:None "GET /v1.25/containers/3f2aee9e458e3a93c36d18d324b6bf165b3880157897b13cbd319a547b095b22/json HTTP/1.1" 200 None
ssh://localhost:None "GET /v1.25/images/my.registry.host/***/hook-express:1.2.1/json HTTP/1.1" 404 133
Pulling hook-express (my.registry.host/***/hook-express:1.2.1)...
Looking for auth config
No auth config in memory - loading from filesystem
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
No config file found
Looking for auth entry for 'my.registry.host'
No entry found
No auth config found
ssh://localhost:None "POST /v1.25/images/create?tag=1.2.1&fromImage=my.registry.host%2F***%2Fhook-express HTTP/1.1" 500 115
Head "https://my.registry.host/v2/***/hook-express/manifests/1.2.1": no basic auth credentials
```

My workflow config is as follows
```yml
 build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2  
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: my.registry.host
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          tags: my.registry.host/1zilc/hook-express:1.2.1
          push: true
      - name: Docker Compose Run
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: up -d
```

docker login is successful, and docker push is also completed
```bash
Run docker/login-action@v1
  with:
    registry: my.registry.host
    username: ***
    password: ***
    logout: true
Logging into my.registry.host...
Login Succeeded!
```
I don’t know where there is a problem with my configuration, I hope to get your help, thanks
