### ISSUE TITLE
Action fails at Execute Over SSH: mkdir -p /github/home/docker-deployment/stacks || true

### ISSUE THREAD

**Issue by alvarolloret** [wshihadeh/docker-deployment-action#23]
I can0t manage to get after the `Execute Over SSH: mkdir -p /github/home/docker-deployment/stacks || true`.... 

This is my action:

```
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.HOST_MANAGER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          stack_file_name: docker-compose.prod.yaml
          args: docker stack deploy --compose-file $FILE --log-level debug --host $HOST
```

this is my output:
```
/usr/bin/docker run --name fa4e140372bcb17b56441a8a806c8e42a5c387_2fe6f5 --label fa4e14 --workdir /github/workspace --rm -e INPUT_REMOTE_DOCKER_HOST -e INPUT_SSH_PRIVATE_KEY -e INPUT_SSH_PUBLIC_KEY -e INPUT_DEPLOYMENT_MODE -e INPUT_COPY_STACK_FILE -e INPUT_STACK_FILE_NAME -e INPUT_ARGS -e INPUT_DEPLOY_PATH -e INPUT_KEEP_FILES -e INPUT_DOCKER_PRUNE -e INPUT_PRE_DEPLOYMENT_COMMAND_ARGS -e INPUT_PULL_IMAGES_FIRST -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/d2e-frontend/d2e-frontend":"/github/workspace" fa4e14:0372bcb17b56441a8a806c8e42a5c387 docker stack deploy --compose-file $FILE --log-level debug --host $HOST
Registering SSH keys...
Agent pid 12
Identity added: /github/home/.ssh/id_rsa (/github/home/.ssh/id_rsa)
Add known hosts
Execute Over SSH: mkdir -p /github/home/docker-deployment/stacks || true
```

I can't see where I'm failing.... any help :)
