### ISSUE TITLE
missing execute_ssh in line 104

### ISSUE THREAD

**Issue by gio1612** [wshihadeh/docker-deployment-action#4]
If use the action without the copy_stack_file, the action get an error:
/docker-entrypoint.sh: line 104: docker-compose: not found

I think is missing the command execute_ssh in the line 104

**Comment by wshihadeh** [comment]
can you share your configs

**Comment by gio1612** [comment]
This is my config

```YAML
name: CI Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Start Docker Deployment
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          # copy_stack_file: true
          deploy_path: /root/deployment-test
          stack_file_name: docker-compose.yml
          args: up -d
```
